package jp.co.xsys.flowoffice.presentation.theme

import androidx.compose.ui.graphics.Color

internal val ReaderPrimaryLight = Color(0xFF1D4ED8)
internal val ReaderOnPrimaryLight = Color(0xFFFFFFFF)
internal val ReaderPrimaryContainerLight = Color(0xFFDCE7FF)
internal val ReaderOnPrimaryContainerLight = Color(0xFF001A43)
internal val ReaderBackgroundLight = Color(0xFFF8FAFC)
internal val ReaderSurfaceLight = Color(0xFFFFFFFF)
internal val ReaderOnSurfaceLight = Color(0xFF172033)
internal val ReaderSurfaceVariantLight = Color(0xFFE7EAF0)
internal val ReaderOutlineLight = Color(0xFF737784)
internal val ReaderErrorLight = Color(0xFFBA1A1A)
internal val ReaderSecondaryLight = Color(0xFF087F5B)
internal val ReaderOnSecondaryLight = Color(0xFFFFFFFF)
internal val ReaderSecondaryContainerLight = Color(0xFFB8F2DC)
internal val ReaderOnSecondaryContainerLight = Color(0xFF002117)
internal val ReaderTertiaryLight = Color(0xFF8A4F00)
internal val ReaderOnTertiaryLight = Color(0xFFFFFFFF)
internal val ReaderTertiaryContainerLight = Color(0xFFFFDDB8)
internal val ReaderOnTertiaryContainerLight = Color(0xFF2C1600)

internal val ReaderPrimaryDark = Color(0xFFB3C5FF)
internal val ReaderOnPrimaryDark = Color(0xFF002C6C)
internal val ReaderPrimaryContainerDark = Color(0xFF1644A6)
internal val ReaderOnPrimaryContainerDark = Color(0xFFDCE7FF)
internal val ReaderBackgroundDark = Color(0xFF10131A)
internal val ReaderSurfaceDark = Color(0xFF171A22)
internal val ReaderOnSurfaceDark = Color(0xFFE2E5EE)
internal val ReaderSurfaceVariantDark = Color(0xFF434650)
internal val ReaderOutlineDark = Color(0xFF9094A0)
internal val ReaderErrorDark = Color(0xFFFFB4AB)
internal val ReaderSecondaryDark = Color(0xFF93D6C0)
internal val ReaderOnSecondaryDark = Color(0xFF00382A)
internal val ReaderSecondaryContainerDark = Color(0xFF00513D)
internal val ReaderOnSecondaryContainerDark = Color(0xFFB8F2DC)
internal val ReaderTertiaryDark = Color(0xFFFFB86B)
internal val ReaderOnTertiaryDark = Color(0xFF492900)
internal val ReaderTertiaryContainerDark = Color(0xFF693C00)
internal val ReaderOnTertiaryContainerDark = Color(0xFFFFDDB8)
